# Generated by Django 4.2.1 on 2023-07-27 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_information_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='Products.product'),
        ),
    ]
